### ISSUE TITLE
Crytyping Support?

### ISSUE THREAD

**Issue by aerickt** [psethwick/plover_fancytext#6]
Randomly repeating characters and dropping semicolons and commas in haphazardly should be sufficient.

https://becca.ooo/crytyper/

**Comment by psethwick** [comment]
I'm gonna try for this, will keep issue updated. Funny feeling that plover won't like it XD

**Comment by psethwick** [comment]
we;;ll I guuessss i.t w.orks

**Comment by psethwick** [comment]
This will definitely go in. I want to tweak the algorithm a bit and implement the rest of it (because why not).
The linked implementation has these:
- swapping two letters
- adding a random letter
- doubling a letter
- adding random punctuation
- deleting a letter
- swapping the case of a letter (e.g. a ⇔ A)

Which is all fairly straightforward. Currently I have repeating letters and adding random punctuation, but the rest is v doable
(will also allow it to take a 'how much' parameter)

**Comment by psethwick** [comment]
I've left out the 'how much' parameter, it should be possible, I'm just done for the day

**Comment by psethwick** [comment]
anyway, it exists now, closing :)
